version: '3'

services:
  db:
    image: mongo:8
    restart: always
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db
